---
- import_tasks: prepare.yml
  when: (f5_ha_status == 'standalone' or (f5_ha_status == 'cluster' and f5_failover_state == 'active'))
  tags: prepare

- import_tasks: configure.yml
  when: (f5_ha_status == 'standalone' or (f5_ha_status == 'cluster' and f5_failover_state == 'active'))
  tags: configure
